// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTElE8PacMOtqawoTEtVbjwFFP65ii9w',
    appId: '1:123114440745:web:36f27631cca74b66a4b438',
    messagingSenderId: '123114440745',
    projectId: 'flutterfirebase-ac343',
    authDomain: 'flutterfirebase-ac343.firebaseapp.com',
    storageBucket: 'flutterfirebase-ac343.firebasestorage.app',
    measurementId: 'G-NB7MJ9151S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj0kOpK2PQwtDrHaPr_Bg5JaHLGTwoH8w',
    appId: '1:123114440745:android:a807c3a6f090daeca4b438',
    messagingSenderId: '123114440745',
    projectId: 'flutterfirebase-ac343',
    storageBucket: 'flutterfirebase-ac343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9EDvc6APiXro4aNweCgergPCuNErmRDc',
    appId: '1:123114440745:ios:36ad5291b9441fb5a4b438',
    messagingSenderId: '123114440745',
    projectId: 'flutterfirebase-ac343',
    storageBucket: 'flutterfirebase-ac343.firebasestorage.app',
    iosBundleId: 'com.example.exempleFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9EDvc6APiXro4aNweCgergPCuNErmRDc',
    appId: '1:123114440745:ios:36ad5291b9441fb5a4b438',
    messagingSenderId: '123114440745',
    projectId: 'flutterfirebase-ac343',
    storageBucket: 'flutterfirebase-ac343.firebasestorage.app',
    iosBundleId: 'com.example.exempleFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbTElE8PacMOtqawoTEtVbjwFFP65ii9w',
    appId: '1:123114440745:web:8cbafbad1889f7d2a4b438',
    messagingSenderId: '123114440745',
    projectId: 'flutterfirebase-ac343',
    authDomain: 'flutterfirebase-ac343.firebaseapp.com',
    storageBucket: 'flutterfirebase-ac343.firebasestorage.app',
    measurementId: 'G-V7HB9ZX1RW',
  );
}
